name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-deploy-workflow:
    if: github.event == 'push' && github.ref_name == 'master'
    uses: .github/workflows/deploy-azure-function.yml@main
    secrets: inherit