name: My Workflow
on: [workflow_dispatch]
#  push:
#    branches:
#      - master
#    paths:
#      - 'devops/**'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Bicep code
        uses: actions/checkout@v3
        with:
          path: repo
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v1
        with:
          template: ./devops/main.bicep
          parameters: ./devops/prodParameters.json