name: Deploy package to Azure Function

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string


env:
  AZURE_FUNCTIONAPP_NAME: gambit-rss-feeder # set this to your application's name

jobs:
  build-and-deploy:
    name: Deploy artifact to Azure Function
    runs-on: windows-latest
    steps:

    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: output

    - name: 'Run Azure Functions action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: 'output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

